### PR TITLE
fix: correct UnmarshalJSON and add MarshalJSON for CloudConfigFile

### LINKED ISSUE #65: [BUG] Encoding mismatch when getting group cloud-init data
**Describe the bug**
Cloud-Init config file is always encoded as `base64`, but encoding is `plain` when getting group data.

**To Reproduce**
1. Fresh cloud-init instance
2. POST data for group `test`:
   ```json
   {
     "description": "The test group",
     "file": {
       "content": "IyMgdGVtcGxhdGU6IGppbmphCiNjbG91ZC1jb25maWcKbWVyZ2VfaG93OgotIG5hbWU6IGxpc3QKICBzZXR0aW5nczogW2FwcGVuZF0KLSBuYW1lOiBkaWN0CiAgc2V0dGluZ3M6IFtub19yZXBsYWNlLCByZWN1cnNlX2xpc3RdCnVzZXJzOgogIC0gbmFtZTogcm9vdAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoge3sgZHMubWV0YV9kYXRhLmluc3RhbmNlX2RhdGEudjEucHVibGljX2tleXMgfX0KZGlzYWJsZV9yb290OiBmYWxzZQo=",
       "encoding": "base64",
       "filename": "string"
     },
     "meta-data": {
       "foo": "bar"
     },
     "name": "test"
   }
   ```
3. POST data for group `test2`:
   ```json
   {
     "description": "The test group",
     "file": {
       "content": "test",
       "encoding": "plain",
       "filename": "string"
     },
     "meta-data": {
       "foo": "bar"
     },
     "name": "test2"
   }
   ```
4. GET `/cloud-init/admin/groups`:
   ```json
   [
     {
       "description": "The test group",
       "file": {
         "content": "SXlNZ2RHVnRjR3hoZEdVNklHcHBibXBoQ2lOamJHOTFaQzFqYjI1bWFXY0tiV1Z5WjJWZmFHOTNPZ290SUc1aGJXVTZJR3hwYzNRS0lDQnpaWFIwYVc1bmN6b2dXMkZ3Y0dWdVpGMEtMU0J1WVcxbE9pQmthV04wQ2lBZ2MyVjBkR2x1WjNNNklGdHViMTl5WlhCc1lXTmxMQ0J5WldOMWNuTmxYMnhwYzNSZENuVnpaWEp6T2dvZ0lDMGdibUZ0WlRvZ2NtOXZkQW9nSUNBZ2MzTm9YMkYxZEdodmNtbDZaV1JmYTJWNWN6b2dlM3NnWkhNdWJXVjBZVjlrWVhSaExtbHVjM1JoYm1ObFgyUmhkR0V1ZGpFdWNIVmliR2xqWDJ0bGVYTWdmWDBLWkdsellXSnNaVjl5YjI5ME9pQm1ZV3h6WlFvPQ==",
         "encoding": "plain",
         "filename": "string"
       },
       "meta-data": {
         "foo": "bar"
       },
       "name": "test"
     },
     {
       "description": "The test group",
       "file": {
         "content": "WkVkV2VtUkJQVDA9",
         "encoding": "plain",
         "filename": "string"
       },
       "meta-data": {
         "foo": "bar"
       },
       "name": "test2"
     }
   ]
   ```
   Notice that both groups have `encoding: plain`, but `content` is base64-encoded.

**Expected behavior**
`encoding: plain` should have plainly-encoded data, `encoding: base64` should have base64-encoded data.

**Additional context**
Tested with latest cloud-init, v1.1.1

### PR DESCRIPTION
**Pull request by synackd**
Closes #65 

Turns out, `UnmarshalJSON()` needed to be revised and a `MarshalJSON()` needed to be added for `CloudConfigFile`. Base64 encoding/decoding caused by `json.Marshal()`/`json.Unmarshal()` was causing mismatches between `CloudConfigFile.Encoding` and the actual encoding of `CloudConfigFile.Content`.

For `UnmarshalJSON()`, continue unmarshalling `Content` into a string, but don't try to base64 decode into the struct. `Encoding` will let the reader know if they need to decode it or not.

For `MarshalJSON()`, use the auxiliary struct like `UnmarshalJSON()` does to convert the bytes to a string so that `json.Marshal()` doesn't try to base64-encode the bytes.

### CODE REVIEW

**Comment by synackd** [comment]
Just for posterity if anyone wants to mess around with variations of the code, I used this for my own testing before testing with cloud-init itself: https://go.dev/play/p/eWegMtwpleC

**Comment by davidallendj** [comment]
Is this related to the automatic encoding/decoding base64 strings that you mentioned earlier today?

**Comment by synackd** [comment]
> Is this related to the automatic encoding/decoding base64 strings that you mentioned earlier today?

Yes. Both the unmarshaller/marshaller functions use an auxiliary struct that has `Content` as a string to mitigate this. Before, only unmarshalling into `CloudConfigFile` prevented unnecessary base64 decoding using the aux struct, but since there was no custom marshalling function to do the same, the bytes were getting base64-encoded in the JSON no matter what`Encoding` was.

> Edit: Iterations 3, 4, and 5 look the same from the go.dev link. What's the different between them? Are these just multiple runs?

Yeah, I was making sure that multiple iterations weren't seeing an endlessly-recurring base64 encode chain.

File: pkg/cistore/models.go [hunk 1]
```diff
@@ -74,33 +72,38 @@ type CloudConfigFile struct {
 
 // Custom unmarshaler for CloudConfigFile
 func (f *CloudConfigFile) UnmarshalJSON(data []byte) error {
-	// Define a helper struct to match the JSON structure
+	// Use temporary struct so json.Unmarshal does not recurse indefinitely.
+	// Also to convert Content from bytes to string so json.Unmarshal
```
Comment (davidallendj) [inline pkg/cistore/models.go:76]: I don't quite understand this comment in relation to what's on line 80 and 90. Is this supposed to be converting `aux.Contents` from bytes to a string in `UnmarshalJSON` because I think I'm seeing the opposite here?

Comment (synackd) [reply pkg/cistore/models.go]: I clarified this a bit in cf9a810. Let me know if it's still unclear.

Comment (davidallendj) [reply pkg/cistore/models.go]: The updated version looks much more clearer now. I only asked because I wanted to make sure I understood what was supposed to be happening.

**Comment by alexlovelltroy** [comment]
Added tests that confirm the behavior I expect.

LGTM

**Review by alexlovelltroy — APPROVED** [review]
LGTM

**Comment by synackd** [comment]
Thanks for adding the tests! Just one small change I added, that being using base64-encoded data instead of plain for the `TestCloudConfigFile_MarshalJSON_Base64` test.
